services:
  vaultwarden:
    container_name: vaultwarden
    image: "vaultwarden/server:1.30.1"
    volumes:
      - vaultwarden_data:/data
    restart: unless-stopped
    ports:
      - 8080:80
volumes:
  vaultwarden_data: {}
