services:
  nodered:
    container_name: nodered
    image: "nodered/node-red:3.1.3"
    volumes:
      - node_red_data:/data
    restart: unless-stopped
    ports:
      - 1880:1880
volumes:
  node_red_data: {}
